### ISSUE TITLE
Enhance sale_order_type to better support mult-company scenario

### ISSUE THREAD

**Issue by kittiu** [OCA/sale-workflow#1185]
As types will be by company, but currently the system do not constrain only type of the company selected in the document.
Now, user select company A can use types of company B. This can lead to user error.
I propose to have followings,

Add @api.constraints('company_id'), to ensure that "type" selected is of that company (or any company), otherwise show warning.
Add domain in field "type", to filter only of that company.
Add @api.onchange('company_id'), when company changes, set "type" to nothing.

Note: these contraints should also be in sale_order_type and purchase_order_type

@watcharaporn-git

**Comment by nicomacr** [comment]
I would also add that if you try to create an invoice in company B having only one type of sale in company A. When trying to create you get a permissions error because it tries to load the unique type of sale that is from the other company.
Same case for sales.

The cause of this problem is [here](https://github.com/OCA/sale-workflow/blob/13.0/sale_order_type/models/account_move.py#L23), this not take account the company of the user.
