### ISSUE TITLE
Discussion about sale_order_price_recalculation

### ISSUE THREAD

**Issue by quentinDupont** [OCA/sale-workflow#1317]
Hello,

We use `sale_order_price_recalculation` module in my company, thanks for the work :)
I have an idea to suggest : would it be nice if the two buttons `recalculate_prices` and `recalculate_names` appears only when changes are made (in prices, discount, description, ?
I find it a bit confusing for user that the two buttons are present in sale order at start even if nothing has changed

![image](https://user-images.githubusercontent.com/9005817/98226630-95742f00-1f56-11eb-8909-609f1f410441.png)

have someone thought about it, advantages and disadvantages of changing that ?

**Comment by skeller1** [comment]
Hi, we also use this addon in our company. :+1: 

My thoughts about your feature request:

AFAIU Recalculate prices or resetting the sale order line descriptions is not for sale order line history tracking. It should be used if you notice wrong descriptions in your product variants, wrong pricelist rules/costs or wrong master data.


One example:
Your company is using different pricelists for each partner and the current default pricelist in res.partner record is not correct (Master Data Management). The quote with 20 sales order lines is already created (no confirmation). The prices are not correct because of the wrong pricelist used in this quote.

What you can do as a sales person?

1. Fix your master data (change the default pricelist in your res.partner record)
2. Change the active pricelist in your current sales order
3. Hit the recalculate button and get correct prices


In this example we have no change in any line of the quote and than the 2 buttons would not be available. This would be bad .....

This is one possible scenario. But there are a lot more ......

I think there's no easy way to detect relevant changes (e.g. changes  in complex pricelist rules with changed start and end dates, expiration dates, changed product variant costs, ...)

This is the responsibility of the sales person (to know what to do). Keep it simple and stupid. Provide a simple solution to correct this business process. These 2 methods are very powerful to boost you daily work without complex implementation.

Thank you.

**Comment by quentinDupont** [comment]
> Hi, we also use this addon in our company. +1
> 
> My thoughts about your feature request:
> 
> AFAIU Recalculate prices or resetting the sale order line descriptions is not for sale order line history tracking. It should be used if you notice wrong descriptions in your product variants, wrong pricelist rules/costs or wrong master data.
> 
> One example:
> Your company is using different pricelists for each partner and the current default pricelist in res.partner record is not correct (Master Data Management). The quote with 20 sales order lines is already created (no confirmation). The prices are not correct because of the wrong pricelist used in this quote.
> 
> What you can do as a sales person?
> 
>     1. Fix your master data (change the default pricelist in your res.partner record)
> 
>     2. Change the active pricelist in your current sales order
> 
>     3. Hit the recalculate button and get correct prices
> 
> 
> In this example we have no change in any line of the quote and than the 2 buttons would not be available. This would be bad .....
> 
> This is one possible scenario. But there are a lot more ......
> 
> I think there's no easy way to detect relevant changes (e.g. changes in complex pricelist rules with changed start and end dates, expiration dates, changed product variant costs, ...)
> 
> This is the responsibility of the sales person (to know what to do). Keep it simple and stupid. Provide a simple solution to correct this business process. These 2 methods are very powerful to boost you daily work without complex implementation.
> 
> Thank you.

Ok thanks for your clear and efficient answer ! It's clearer for me now and I like the "Keep it simple and stupid" point of view :ok_hand:
