### ISSUE TITLE
[14.0] sale_order_revision: issue at SO creation

### ISSUE THREAD

**Issue by simahawk** [OCA/sale-workflow#1658]
Originate from https://github.com/OCA/sale-workflow/pull/1657

@kittiu I see you've migrated the module and before [this migration](https://github.com/OCA/sale-workflow/commit/4a38fcf20fcf55f115b36ccdf764ff48c15e91ca#diff-2b7f646de13a325a8564bc11e174f489a505e97bb29a567bbdbf576e222cb19e) a sequence was used.

IMO when we create the order first we should not trigger any revision machinery. The `unrevisioned_name` should probably be a computed stored field and depend on `name`.

What do you think?

Relates to #1116

**Comment by kittiu** [comment]
Noted, let me try to understand this. You are saying that, this PR need to add this line,
https://github.com/nilshamerlinck/sale-workflow/blob/14.0-fix-sale_stock_picking_blocking-tests/sale_stock_picking_blocking/tests/test_sale_stock_picking_blocking.py#L43

Because without it, test error result from module sale_order_revision.

Correct?

**Comment by kittiu** [comment]
I have tested as following on v14
1. Install sale_order_revision
2. Install sale_stock_picking_blocking, remove the line in so_dict.
3. run test on the later, seem OK.

Also test install,
1. Install sale_isolated_quotation
2. Install sale_order_revision
3. And it seem OK too.

Can you provide step to error? Thanks!

**Comment by nilshamerlinck** [comment]
Hi @kittiu @simahawk I think I finally understood the issue better:
- both `sale_isolated_quotation` and `sale_quotation_number` define a `sale.quotation` sequence, respectively [here](https://github.com/OCA/sale-workflow/blob/14.0/sale_isolated_quotation/data/ir_sequence_data.xml#L6) and [here](https://github.com/OCA/sale-workflow/blob/14.0/sale_quotation_number/data/data.xml#L12)
- as such, they are [incompatible and should not be installed together](https://github.com/OCA/sale-workflow/pull/1664)
- the tests failure I was facing the other day with `sale_stock_picking_blocking` is not due to the module itself, but to the fact that [`env["ir.sequence"].next_by_code("sale.quotation")`](https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/models/ir_sequence.py#L282) is non-deterministic: SELECT results not being ordered by id here, the call will return either the first or the second `sale.quotation` sequence
- as a consequence, it is possible to reach a collision: "SQ010" created during tests, while already existing as a demo sale quotation, hence the misleading error:
```
ERROR: duplicate key value violates unique constraint "sale_order_revision_unique"
DETAIL:  Key (unrevisioned_name, revision_number, company_id)=(SQ010, 0, 1) already exists.
```

I reverted the temporary workaround [here](https://github.com/OCA/sale-workflow/pull/1663).

Let me know if you think of a different appropriate set of actions :)

**Comment by kittiu** [comment]
I think this is a proper solution. Thanks.

**Comment by pedrobaeza** [comment]
Another option is to rename one of the sequence codes.

**Comment by simahawk** [comment]
> Another option is to rename one of the sequence codes.

yeah, wouldn't be better?

**Comment by nilshamerlinck** [comment]
These modules are very similar in their functional purpose, with a subtle difference:
- `sale_isolated_quotation`: Create quotation > SQ001 > Convert to order > SQ001 Locked > New record SO001 is created, linked to SQ001
- `sale_quotation_number`: Create quotation > SQ001 > Confirm > Record SQ001 becomes SO001

But they are incompatible in the sense that, beyond the sequence duplicate, nobody would reasonably want to have both of them installed:
- Create quotation > SQ001 > Convert to order > Locked > New record SQ002 is created

To enforce that, I updated the [PR](https://github.com/OCA/sale-workflow/pull/1664) to add excludes entries in their manifests.

**Comment by kittiu** [comment]
Question:
In the addon it self. Are there practice to give warning when install module A and to ensure module B not already exists?
Can we use pre install hooks? Or something to declare in __manifest__.py ?

**Comment by nilshamerlinck** [comment]
Hi @kittiu 

Yes, thanks to the ["excludes" entries](https://github.com/odoo/odoo/commit/6498f351451081de0440d7f6293bd547d56c74d2), an error will be raised if user tries to install both modules:

![error](https://user-images.githubusercontent.com/511258/126734162-9de8812f-b385-4280-aaab-49b9a1591edf.png)

**Comment by simahawk** [comment]
> Hi @kittiu
> 
> Yes, thanks to the ["excludes" entries](https://github.com/odoo/odoo/commit/6498f351451081de0440d7f6293bd547d56c74d2), an error will be raised if user tries to install both modules:
> 
> ![error](https://user-images.githubusercontent.com/511258/126734162-9de8812f-b385-4280-aaab-49b9a1591edf.png)

@nilshamerlinck  great, seems really the way to go. Thanks for digging into it.

Please check my comments on the PR.

**Comment by bodedra** [comment]
> Question:
> In the addon it self. Are there practice to give warning when install module A and to ensure module B not already exists?
> Can we use pre install hooks? Or something to declare in **manifest**.py ?

FYI, https://github.com/OCA/maintainer-tools/pull/421
