### ISSUE TITLE
sale_order_product_picker: editing amount and discarding is insconsistent

### ISSUE THREAD

**Issue by yajo** [OCA/sale-workflow#2843]
## Module
sale_order_product_picker

## Describe the bug
When the user saves a value, and then edits again and discards, there's an inconsistency in the value that is stored in Odoo.

## To Reproduce
**Affected versions**: 16

https://github.com/OCA/sale-workflow/assets/973709/998c7857-fb47-42e5-8c03-56eb678d4cc0

**Expected behavior**
Discarding edits should restore the state of the last edit, not the sate of the order line before any edits. Just like normal Odoo.

**Additional context**
Tested on runboat.

@moduon MT-4396

**Comment by rafaelbn** [comment]
@CarlosRoca13 @sergio-teruel could you take a look on this please? Just know your opinion. Thank you! 😄

**Comment by CarlosRoca13** [comment]
Sorry for the delay, I had lost the email :sweat: This problem is not related with the picker... It is a bug of odoo. In next gif, you will see the same approach in a sale order without the picker installed:

![bug](https://github.com/OCA/sale-workflow/assets/35952655/02e6a189-23dd-4a39-8961-22b4a623a67e)

**Comment by CarlosRoca13** [comment]
I have made a PR to Odoo to try to resolve this issue: https://github.com/odoo/odoo/pull/171703

**Comment by CarlosRoca13** [comment]
Odoo accepted the changes and will be solved when merging this pr https://github.com/odoo/odoo/pull/172233

**Comment by yajo** [comment]
I see it's merged, so we can close here. Thanks!
