### ISSUE TITLE
Sale rental in version 8 is not working

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/sale-workflow#344]
Sale rental in version 8 is not working.
There is a video in Youtube , published by the author Alexis de Lattre, explaining how to use the module in version 7.

In version 8 I can not see the delivery order (the product is a service so there is not stock movemet)

The quotation is different, it does not count days between dates.

The rentals database has no lines added.

**Comment by alexis-via** [comment]
You should try with this code, which is the latest for v8 : https://github.com/OCA/sale-workflow/pull/273  (the code in the main repo is quite old and lacks several fixes)

Or you could try on v9 with this code: https://github.com/OCA/sale-workflow/pull/353
I know it works because I made it last week.

**Comment by pedrobaeza** [comment]
Answered, so I close.
