### ISSUE TITLE
[10.0] merge sale_payment_method and sale_quick_payment in one module

### ISSUE THREAD

**Issue by mourad-ehm** [OCA/sale-workflow#410]
@florian-dacosta  proposed to merge  sale_payment_method and sale_quick_payment in one module in v 9.0 (see #403 ).
I propose to make to same for v 10.0.
The views of the contributors to this module are welcome:
@sebastienbeau 
@guewen 
@bguillot 
@lepistone 
@gurneyalex 
@damdam-s 
@JosDeGraeve

**Comment by lepistone** [comment]
Hi! I don't work on this anymore. I support the positions of the other contributors.Thanks!

**Comment by pedrobaeza** [comment]
Can you tell about the arguments for the join?

**Comment by florian-dacosta** [comment]
The module sale_payment_method from v8 implement a few features we do not require in v9 and +.

First, the payment_method model is replaced by the account_payment_mode model from https://github.com/OCA/bank-payment repository. Before, we had 2 models for the same thing...

Second, The sale_payment_module was implementing a way to add payment for a sale order, in order to be re-used in sale_quick_payment but we now use the new native model 'account.payment'.
It is already used to add payment from invoice and we use it to make payment from sale order.

This was the 2 main features brought by sale_payment_method. As both are obsolete, I think there is no need to keep 2 modules. And anyway, the module sale_payment_method could not keep his name (since the payment.method model is gone), so it is the occasion to rename and keep one module.
