### ISSUE TITLE
[10.0] [sale_exception]: Exception detection broken?

### ISSUE THREAD

**Issue by iia** [OCA/sale-workflow#874]
Hi,

While confirming sale orders I'm getting the following exception:

> Error while validating constraint
> 
> Mixing apples and oranges: sale.order.line(36246, 36245, 36247, 36248, 36254, 36249, 36250, 36251, 36252, 36255, 36253) & sale.order()

It seems like this is caused by this [commit](https://github.com/OCA/sale-workflow/commit/f669d2607164dfb38639c5604b73b0157789f1b0).

To be more precise, in the file **sale.py** the following changes seem to be causing this.

```
@api.multi
def detect_exceptions(self):
	all_exceptions = super(SaleOrder, self).detect_exceptions()
	lines = self.mapped('order_line')
	all_exceptions += lines.detect_exceptions()
	return all_exceptions
```

The line, `all_exceptions += lines.detect_exceptions()` is calling sale order line exception detection from sale order's exception detection method. Shouldn't this method be called from its own model class?

**Comment by daramousk** [comment]
Hello Ishraq and thank you for taking time to write this,

When you have an error of any kind, please do share the whole stack trace so that we can help more easily and reproduce the error. That way we can be sure and not speculate.

Now, from what I see the `detect_exceptions` returns an array with ids of the rules that where broken (ie. records of `exception.rule`) so I cannot see how this can throw this error.

Can you reproduce and share the whole stack please?
