### ISSUE TITLE
12.0 build failing

### ISSUE THREAD

**Issue by dreispt** [OCA/sale-workflow#972]
Last successful build was from Oct14.
The next build, on Oct17, did no changes to code and failed.
The cause might be upstream.
Build [fails](https://travis-ci.org/OCA/sale-workflow/jobs/598798477#L1438) on `odoo.addons.sale_exception.tests.test_multi_records` tests.

**Comment by dreispt** [comment]
I seems that Runbot build are also broken - you can login the first time, but later logins will present you no menu option available.

**Comment by pedrobaeza** [comment]
I have disable the test for now, as it's blocking a lot of PRs, in b553fe09e2ae3ec66283d9687abb7aebd627ea1b, but I reopen again as it's not solved at all.

**Comment by pedrobaeza** [comment]
@ivantodorovich do you know what's happening?

**Comment by ivantodorovich** [comment]
There is a bug, and I could track it to that commit: https://github.com/OCA/server-tools/commit/43def640a93cbdcb9275feaf9cd4efa6dbbd026a

The exceptions are being triggered, but exception_ids appears to be empty. That's why tests are failing.

![image](https://user-images.githubusercontent.com/1914185/67553944-a6b51980-f70e-11e9-976a-a8d2d4c72627.png)

![image](https://user-images.githubusercontent.com/1914185/67553955-af0d5480-f70e-11e9-9c2b-09ea50b3f9f6.png)

@guewen can you check?
